//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusConnection
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> Q { get; set; }
        public int BusId { get; set; }
    
        public virtual Bus Bus { get; set; }
    }
}
