//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Bus
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Bus()
    {
        this.BusConnections = new HashSet<BusConnection>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public int Voltage { get; set; }
    public System.DateTime Installed { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BusConnection> BusConnections { get; set; }
}

public partial class BusConnection
{
    public int Id { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public Nullable<double> P { get; set; }
    public Nullable<double> Q { get; set; }
    public int BusId { get; set; }

    public virtual Bus Bus { get; set; }
}
